SCENARIOS = [
    {
        "district": "Napa",
        "signals": [
            {"type": "RSS", "source": "CAL_FIRE", "text": "Immediate Evacuation Order for silverado trail. Fire jumping containment lines."},
            {"type": "Twitter", "source": "User1", "text": "My whole neighborhood is evacuating! Ash falling everywhere. #NapaFire"},
            {"type": "RSS", "source": "WILDFIRE_TODAY", "text": "Glass Fire explodes to 10,000 acres in 4 hours. extreme rates of spread."}
        ],
        "ai_state": {
            "headline": "Erratic fire behavior with spotting up to 1 mile threatens multiple structures in Napa Valley.",
            "deep_summary": "The Napa Valley Fire Complex is exhibiting extremely dangerous and erratic behavior, with embers spotting up to a mile ahead of the main front. Multiple structures are currently under immediate threat, and mandatory evacuations are in place for over 2,000 residents. Fire crews are focusing on structure protection as wind conditions remain unfavorable.",
            "magnitude": 9,
            "response_status": "Act",
            "power_status": "Down",
            "water_status": "Partially Damaged",
            "comms_status": "Partially Damaged",
            "district_code": "NAP-01",
            "geographic_center": "St. Helena, CA",
            "certainty_score": 95,
            # Old Text Fields (Compat)
            "human_safety_summary": "Mandatory evacuations for 2,000+ residents. 1 injury reported.",
            "infrastructure_summary": "Power cut to 50k customers. Hwy 29 closed.",
            "intensity_summary": "Extreme. 10k acres. 0% contained. Crown runs observed.",
            "environmental_summary": "AQI 300+. Zero visibility.",
            "operational_summary": "CalFire Team 1 activated. Requesting 50 Type-3 engines.",
            # New Numerical Fields
            "fatalities": 0,
            "injured": 1,
            "people_threatened": 2500,
            "structures_destroyed": 5,
            "structures_threatened": 500,
            "infra_impact_score": 85,
            "acres_burned": 10500,
            "containment_pct": 0,
            "aqi": 310,
            "personnel_count": 450,
            "apparatus_count": 65
        }
    },
    {
        "district": "Shasta",
        "signals": [
            {"type": "RSS", "source": "CAL_FIRE", "text": "Zogg Fire showing moderate activity. Forward progress slowed."},
            {"type": "Twitter", "source": "User2", "text": "Smoke is clearing up a bit in Redding. #ZoggFire"}
        ],
        "ai_state": {
            "headline": "Vegetation fire holding at ridges with crews making good progress on containment lines.",
            "deep_summary": "The Zogg Fire is currently holding at the main ridge lines, aided by calming wind conditions. Fire crews have established solid anchor points and are making good progress on constructing containment lines. While evacuation warnings remain for nearby communities, the immediate threat to life and property has significantly diminished.",
            "magnitude": 6,
            "response_status": "Watch",
            "power_status": "Functional",
            "water_status": "Functional",
            "comms_status": "Functional",
            "district_code": "SHU-04",
            "geographic_center": "Redding, CA",
            "certainty_score": 88,
            "human_safety_summary": "Evacuation warnings remain. No immediate threat to life.",
            "infrastructure_summary": "No damage to critical infra. Local roads open.",
            "intensity_summary": "Moderate. 500 acres. 20% contained.",
            "environmental_summary": "AQI 100. Winds calming.",
            "operational_summary": "Mop up operations beginning on south flank.",
            # New Numerical Fields
            "fatalities": 0,
            "injured": 0,
            "people_threatened": 100,
            "structures_destroyed": 0,
            "structures_threatened": 20,
            "infra_impact_score": 10,
            "acres_burned": 520,
            "containment_pct": 25,
            "aqi": 95,
            "personnel_count": 120,
            "apparatus_count": 14
        }
    },
    {
        "district": "San Diego",
        "signals": [
            {"type": "Twitter", "source": "SD_Scanner", "text": "Small brush fire near I-5. Firefighters on scene."},
            {"type": "RSS", "source": "LAFD", "text": "Vegetation fire, 2 acres. No structural threat."}
        ],
        "ai_state": {
            "headline": "Small roadside fire near I-5 causing traffic delays but no structural threat.",
            "deep_summary": "A small vegetation fire ignited near the I-5 corridor, likely due to a vehicle spark. Firefighters are on scene and handling the incident effectively with mobile attack units. Traffic is backed up significantly, but there is no threat to nearby structures or communities at this time.",
            "magnitude": 3,
            "response_status": "Monitor",
            "power_status": "Functional",
            "water_status": "Functional",
            "comms_status": "Functional",
            "district_code": "SD-10",
            "geographic_center": "Oceanside, CA",
            "certainty_score": 80,
            "human_safety_summary": "None. Traffic impact only.",
            "infrastructure_summary": "None.",
            "intensity_summary": "Low. 2 acres. 80% contained.",
            "environmental_summary": "Clear.",
            "operational_summary": "2 Engines dispatched. Released within hour.",
            # New Numerical Fields
            "fatalities": 0,
            "injured": 0,
            "people_threatened": 0,
            "structures_destroyed": 0,
            "structures_threatened": 0,
            "infra_impact_score": 5,
            "acres_burned": 2,
            "containment_pct": 80,
            "aqi": 35,
            "personnel_count": 12,
            "apparatus_count": 3
        }
    },
    {
        "district": "Tahoe",
        "signals": [
            {"type": "RSS", "source": "InciWeb", "text": "Caldor Fire: 100% Contained. Transitioning to patrol status."},
        ],
        "ai_state": {
            "headline": "Tahoe Basin",
            "deep_summary": "Fire fully contained. Rehabilitation work in progress.",
            "magnitude": 1,
            "response_status": "Resolved",
            "power_status": "Functional",
            "water_status": "Functional",
            "comms_status": "Functional",
            "district_code": "ELK-02",
            "geographic_center": "South Lake Tahoe, CA",
            "certainty_score": 99,
            "human_safety_summary": "All zones repopulated.",
            "infrastructure_summary": "Restoration crews active.",
            "intensity_summary": "None. Cold trail.",
            "environmental_summary": "Good.",
            "operational_summary": "Patrol status only.",
            # New Numerical Fields
            "fatalities": 0,
            "injured": 0,
            "people_threatened": 0,
            "structures_destroyed": 0,
            "structures_threatened": 0,
            "infra_impact_score": 0,
            "acres_burned": 0,
            "containment_pct": 100,
            "aqi": 15,
            "personnel_count": 5,
            "apparatus_count": 1
        }
    },
    {
        "district": "Los Angeles",
        "signals": [
            {"type": "Twitter", "source": "MalibuSafety", "text": "Fast moving grass fire near PCH and Topanga. Traffic stopped."},
            {"type": "RSS", "source": "LAFD", "text": "Topanga Incident: 50 acres, rapid rate of spread towards structures."}
        ],
        "ai_state": {
            "headline": "Rapidly moving grass fire driven by onshore winds is impacting PCH and threatening homes.",
            "deep_summary": "A fast-moving grass fire, fueled by stiff onshore winds, is spreading rapidly near Topanga Canyon. The fire has impacted Pacific Coast Highway (PCH), forcing its closure in both directions and creating a bottleneck for evacuations. several beach homes are under immediate threat, and air tankers are currently conducting drops to slow the forward spread.",
            "magnitude": 6,
            "response_status": "Act",
            "power_status": "Functional",
            "water_status": "Functional",
            "comms_status": "Functional",
            "district_code": "LAC-14",
            "geographic_center": "Malibu, CA",
            "certainty_score": 90,
            "human_safety_summary": "Beach homes under threat. Evacuation warning for Topanga Canyon.",
            "infrastructure_summary": "PCH closed in both directions.",
            "intensity_summary": "High spread rate in light fuels.",
            "environmental_summary": "Smoke impacting LA basin.",
            "operational_summary": "Air tankers dropping retardant. 10 Engines on scene.",
            # New Numerical Fields
            "fatalities": 0,
            "injured": 0,
            "people_threatened": 400,
            "structures_destroyed": 1,
            "structures_threatened": 50,
            "infra_impact_score": 40,
            "acres_burned": 55,
            "containment_pct": 10,
            "aqi": 120,
            "personnel_count": 80,
            "apparatus_count": 15
        }
    },
    {
        "district": "Yosemite",
        "signals": [
            {"type": "RSS", "source": "NPS_Fire", "text": "Lightning strike detected in high country near Tuolumne Meadows."},
            {"type": "Twitter", "source": "Hiker1", "text": "Small smoke column visible from Lembert Dome. #Yosemite"}
        ],
        "ai_state": {
            "headline": "Yosemite High Country",
            "deep_summary": "Remote lightning start. Low threat to developed areas.",
            "magnitude": 2,
            "response_status": "Monitor",
            "power_status": "Functional",
            "water_status": "Functional",
            "comms_status": "Functional",
            "district_code": "YOS-05",
            "geographic_center": "Tuolumne Meadows, CA",
            "certainty_score": 75,
            "human_safety_summary": "None. Backcountry trails advised closed.",
            "infrastructure_summary": "None.",
            "intensity_summary": "Low. Creeping fire behavior.",
            "environmental_summary": "Minimal smoke.",
            "operational_summary": "Monitoring via aircraft. Allow natural burn policy considered.",
            # New Numerical Fields
            "fatalities": 0,
            "injured": 0,
            "people_threatened": 0,
            "structures_destroyed": 0,
            "structures_threatened": 0,
            "infra_impact_score": 0,
            "acres_burned": 5,
            "containment_pct": 0,
            "aqi": 25,
            "personnel_count": 0,
            "apparatus_count": 0
        }
    },
    {
        "district": "Riverside",
        "signals": [
            {"type": "RSS", "source": "CAL_FIRE_RRU", "text": "Rabbit Fire: 500 acres. Zero containment. Threatening structures in Moreno Valley."},
            {"type": "Twitter", "source": "SoCalScanner", "text": "Major wind driven fire in Riverside! massive header nearby."}
        ],
        "ai_state": {
            "headline": "Dangerous wind-driven fire poses immediate threat to suburban tract housing in Moreno Valley.",
            "deep_summary": "A critical wind event is driving the Rabbit Fire rapidly towards densely populated suburban neighborhoods in Moreno Valley. Zero containment has been achieved so far, and the fire is spotting well ahead of the main front. Immediate evacuation orders have been issued for Zone 3, with over 5,000 residents impacted and power lines reported down in the area.",
            "magnitude": 8,
            "response_status": "Act",
            "power_status": "Partially Damaged",
            "water_status": "Functional",
            "comms_status": "Functional",
            "district_code": "RRU-22",
            "geographic_center": "Moreno Valley, CA",
            "certainty_score": 96,
            "human_safety_summary": "Immediate Evacuation Order for Zone 3. 500 homes threatened.",
            "infrastructure_summary": "Power lines sparking report. Suburban roads gridlocked.",
            "intensity_summary": "Extreme. Spotting ahead of main front.",
            "environmental_summary": "High dust and smoke.",
            "operational_summary": "All available engines requested. Strike teams assembling.",
            # New Numerical Fields
            "fatalities": 0,
            "injured": 2,
            "people_threatened": 5000,
            "structures_destroyed": 12,
            "structures_threatened": 1500,
            "infra_impact_score": 60,
            "acres_burned": 2500,
            "containment_pct": 5,
            "aqi": 250,
            "personnel_count": 200,
            "apparatus_count": 45
        }
    },
    {
        "district": "Monterey",
        "signals": [
            {"type": "RSS", "source": "USFS", "text": "Colorado Fire: Slip out on coastal ridge. Difficult access."},
        ],
        "ai_state": {
            "headline": "Big Sur Coast",
            "deep_summary": "Fire in steep terrain. Difficult access for ground crews.",
            "magnitude": 4,
            "response_status": "Monitor",
            "power_status": "Functional",
            "water_status": "Functional",
            "comms_status": "Functional",
            "district_code": "LPN-09",
            "geographic_center": "Big Sur, CA",
            "certainty_score": 85,
            "human_safety_summary": "Campgrounds advised to close.",
            "infrastructure_summary": "Hwy 1 open but smoke visible.",
            "intensity_summary": "Moderate backing fire.",
            "environmental_summary": "Sensitive coastal habitat involved.",
            "operational_summary": "Handcrews hiking in. Heli-bucket support.",
             # New Numerical Fields
            "fatalities": 0,
            "injured": 0,
            "people_threatened": 50,
            "structures_destroyed": 0,
            "structures_threatened": 0,
            "infra_impact_score": 5,
            "acres_burned": 15,
            "containment_pct": 10,
            "aqi": 45,
            "personnel_count": 40,
            "apparatus_count": 2
        }
    },
    {
        "district": "Alameda",
        "signals": [
            {"type": "Twitter", "source": "OaklandUser", "text": "Smoke smelling strong in the hills! Sirens everywhere!"},
            {"type": "RSS", "source": "EastBayTimes", "text": "Fire Reported near Grizzly Peak. Firefighters responding to 2-alarm vegetation fire."}
        ],
        "ai_state": {
            "headline": "Vegetation fire in urban-interface zone raises high concern due to density and history.",
            "deep_summary": "A vegetation fire has broken out in the Oakland Hills urban-interface zone, triggering a massive response due to the area's tragic fire history and high housing density. Smoke is visible throughout the Bay Area, and firefighters are engaging in an aggressive initial attack to prevent the fire from establishing in the canopy. Advisory evacuations are being broadcast for Skyline Blvd residents.",
            "magnitude": 7,
            "response_status": "Act",
            "power_status": "Functional",
            "water_status": "Functional",
            "comms_status": "Functional",
            "district_code": "OAK-03",
            "geographic_center": "Oakland Hills, CA",
            "certainty_score": 92,
            "human_safety_summary": "Advisory evacuations for Skyline Blvd.",
            "infrastructure_summary": "Dense urban roads adjacent to fire.",
            "intensity_summary": "Moderate to High. Potential for structure ignition.",
            "environmental_summary": "Smoke over bay area.",
            "operational_summary": "Aggressive initial attack. Mutual aid from Berkeley responding.",
             # New Numerical Fields
            "fatalities": 0,
            "injured": 0,
            "people_threatened": 1500,
            "structures_destroyed": 0,
            "structures_threatened": 300,
            "infra_impact_score": 25,
            "acres_burned": 10,
            "containment_pct": 15,
            "aqi": 85,
            "personnel_count": 100,
            "apparatus_count": 25
        }
    },
    {
        "district": "Siskiyou",
        "signals": [
            {"type": "RSS", "source": "KlamathNF", "text": "Head Fire: Rapid growth in timber. Threatening major transmission lines."},
        ],
        "ai_state": {
            "headline": "Siskiyou Complex",
            "deep_summary": "Major timber fire with long range spotting. Critical infrastructure threat.",
            "magnitude": 8,
            "response_status": "Act",
            "power_status": "Down",
            "water_status": "Functional",
            "comms_status": "Partially Damaged",
            "district_code": "SKU-55",
            "geographic_center": "Yreka, CA",
            "certainty_score": 94,
            "human_safety_summary": "Evacuation orders for rural communities.",
            "infrastructure_summary": "Major north-south transmission lines compromised.",
            "intensity_summary": "Extreme. Crown fire in timber.",
            "environmental_summary": "Heavy smoke impacting Oregon border.",
            "operational_summary": "Type 1 IMT requested.",
             # New Numerical Fields
            "fatalities": 0,
            "injured": 0,
            "people_threatened": 200,
            "structures_destroyed": 1,
            "structures_threatened": 20,
            "infra_impact_score": 90,
            "acres_burned": 8000,
            "containment_pct": 0,
            "aqi": 200,
            "personnel_count": 300,
            "apparatus_count": 40
        }
    },
    {
        "district": "San Bernardino",
        "signals": [
            {"type": "Twitter", "source": "ParkRanger", "text": "Small brush fire near Jumbo Rocks. Visitors please stay clear."},
        ],
        "ai_state": {
            "headline": "Small fire in desert scrub showing slow movement with minimal threat to park resources.",
            "deep_summary": "A small fire has been detected in the high desert scrub near Jumbo Rocks. The fire is moving slowly due to sparse fuels and lack of wind. Park Rangers are monitoring the situation, and campgrounds have been evacuated as a precaution, but no significant damage to the park's iconic Joshua Trees or infrastructure is expected at this time.",
            "magnitude": 2,
            "response_status": "Monitor",
            "power_status": "Functional",
            "water_status": "Functional",
            "comms_status": "Functional",
            "district_code": "JTR-01",
            "geographic_center": "Joshua Tree NP, CA",
            "certainty_score": 88,
            "human_safety_summary": "Campground evacuation as precaution.",
            "infrastructure_summary": "None.",
            "intensity_summary": "Low. Sparse fuels.",
            "environmental_summary": "Threat to Joshua Trees.",
            "operational_summary": "Park service handling.",
             # New Numerical Fields
            "fatalities": 0,
            "injured": 0,
            "people_threatened": 50,
            "structures_destroyed": 0,
            "structures_threatened": 0,
            "infra_impact_score": 0,
            "acres_burned": 1,
            "containment_pct": 50,
            "aqi": 20,
            "personnel_count": 4,
            "apparatus_count": 1
        }
    }
]
